"""updated password type

Revision ID: c198d71fc338
Revises: 767378f84827
Create Date: 2024-10-31 21:57:14.669947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c198d71fc338'
down_revision: Union[str, None] = '767378f84827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=120),
               type_=sa.LargeBinary(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.LargeBinary(),
               type_=sa.String(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###
